name: Release (Tag -> GHCR)

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io

jobs:
  push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image name (lowercase)
        # Converts OWNER/REPO to lowercase: required by GHCR
        run: echo "IMAGE_NAME=${{ env.REGISTRY }}/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (version + latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:latest
          # optional: build cache
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # print image reference for logs
      - name: Show image tags
        run: |
          echo "Pushed:"
          echo "${{ env.IMAGE_NAME }}:${{ github.ref_name }}"
          echo "${{ env.IMAGE_NAME }}:latest"
